struct v2f
{
    float4 Position : POSITION; //in projection space
    float4 Color : COLOR;
    float4 TexCoords : TEXCOORD0;
    float4 Normal : TEXCOORD1;
    float2 Alpha : TEXCOORD2;
};

float4 main(v2f IN, uniform sampler1D colorMap : TEXUNIT0) : COLOR
{
	float u = (IN.Alpha.x / 256.0f) + (1.0f / 512.0f);
	float4 sample = tex1D(colorMap, u);
	sample *= IN.Alpha.y;
	return sample;
}