#include "VertexFormats.cg"

v2f main(a2v IN, uniform float4x4 world, uniform float4x4 viewProj)
{    
	//The  transformation is performed in two stages to *precisely* match
	//what the other vertex program does. Otherwise z-fighting can result.
	v2f OUT;
    OUT.Position = mul(world, IN.Position);
    OUT.Position = mul(viewProj, OUT.Position);
	
#ifdef ASSIGN_MATERIAL
	OUT.Alpha = IN.Alpha;
#endif
    return OUT;
}

