void AmbientVP(float4 position : POSITION,
						  float2 uv		  : TEXCOORD0,
						  
						  out float4 oPosition : POSITION,
						  out float2 oUv	   : TEXCOORD0,
						  out float4 colour    : COLOR,

						  uniform float4x4 world,
						  uniform float4x4 viewProj,
						  uniform float4 ambient)
{
	oPosition = mul(world, position);
	oPosition = mul(viewProj, oPosition);
	colour = ambient;
}